# Generated by Django 6.0 on 2025-12-06 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "package_number",
                    models.CharField(
                        help_text="Unique package identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("BOX", "Box"),
                            ("PALLET", "Pallet"),
                            ("CONTAINER", "Container"),
                            ("ENVELOPE", "Envelope"),
                        ],
                        default="BOX",
                        help_text="Type of package",
                        max_length=20,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Package length in cm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Package width in cm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Package height in cm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "empty_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Weight of empty package in kg",
                        max_digits=8,
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total weight including contents in kg",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum allowed weight for this package type",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_sealed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Package notes or special handling instructions",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional package metadata",
                    ),
                ),
            ],
            options={
                "ordering": ["packing_task", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="Unique order identifier (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("APPROVED", "Approved"),
                            ("ALLOCATED", "Allocated"),
                            ("PICKING", "Picking"),
                            ("PACKING", "Packing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CREATED",
                        help_text="Current order status in the fulfillment workflow",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Order priority level",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Order subtotal before taxes/shipping",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax amount",
                        max_digits=12,
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Shipping cost",
                        max_digits=12,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total order amount",
                        max_digits=12,
                    ),
                ),
                (
                    "warehouse_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Assigned warehouse UUID (placeholder for Warehouse module integration)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Order notes or special instructions"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional flexible metadata (shipping preferences, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who placed the order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated the order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_id",
                    models.UUIDField(
                        help_text="Product UUID (placeholder for Product module integration)"
                    ),
                ),
                (
                    "product_sku",
                    models.CharField(
                        help_text="Product SKU for inventory tracking", max_length=100
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Product name at time of order", max_length=255
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Original quantity ordered by customer",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_allocated",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Quantity allocated/reserved in inventory",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_picked",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Quantity picked from warehouse",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_packed",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Quantity packed into packages",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_shipped",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Quantity shipped",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price per unit", max_digits=12
                    ),
                ),
                (
                    "unit_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Weight per unit (kg)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for this line item (quantity_ordered * unit_price)",
                        max_digits=12,
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Total weight for this line item",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional item-specific metadata",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order_fulfillment.order",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "product_sku"],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "warehouse_id",
                    models.UUIDField(
                        help_text="Warehouse UUID (placeholder for Warehouse module integration)"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Specific warehouse location (aisle, shelf, bin, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity reserved at this location",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved"),
                            ("RELEASED", "Released"),
                            ("CONSUMED", "Consumed"),
                        ],
                        default="RESERVED",
                        help_text="Current allocation status",
                        max_length=20,
                    ),
                ),
                (
                    "reservation_id",
                    models.CharField(
                        help_text="External reservation ID from inventory system",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Allocation notes or special handling instructions",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order this allocation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="order_fulfillment.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="Order item this allocation is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="order_fulfillment.orderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-allocated_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity of this item in the package",
                        max_digits=12,
                    ),
                ),
                (
                    "position_x",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="X position in package (for pallets/containers)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "position_y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Y position in package (for pallets/containers)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "position_z",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Z position in package (for pallets/containers)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="Order item in this package",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="order_fulfillment.orderitem",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="Package containing this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="order_fulfillment.package",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_number",
                    models.CharField(
                        help_text="Unique packing task identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NOT_STARTED",
                        help_text="Current packing task status",
                        max_length=20,
                    ),
                ),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("completed_items", models.PositiveIntegerField(default=0)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Packing task notes or special instructions",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order this packing task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_tasks",
                        to="order_fulfillment.order",
                    ),
                ),
                (
                    "packer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Warehouse staff assigned to this packing task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_packing_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="package",
            name="packing_task",
            field=models.ForeignKey(
                help_text="Packing task this package belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="order_fulfillment.packingtask",
            ),
        ),
        migrations.CreateModel(
            name="PickingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_number",
                    models.CharField(
                        help_text="Unique picking task identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NOT_STARTED",
                        help_text="Current picking task status",
                        max_length=20,
                    ),
                ),
                (
                    "warehouse_id",
                    models.UUIDField(help_text="Warehouse UUID where picking occurs"),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        help_text="Warehouse zone for this task",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Task priority",
                        max_length=10,
                    ),
                ),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("completed_items", models.PositiveIntegerField(default=0)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Picking task notes or special instructions",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order this picking task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking_tasks",
                        to="order_fulfillment.order",
                    ),
                ),
                (
                    "picker",
                    models.ForeignKey(
                        blank=True,
                        help_text="Warehouse staff assigned to this picking task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_picking_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickingItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_to_pick",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity that should be picked",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_picked",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Quantity actually picked",
                        max_digits=12,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Warehouse location where item should be picked from",
                        max_length=100,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("picked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="Order item being picked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking_items",
                        to="order_fulfillment.orderitem",
                    ),
                ),
                (
                    "picking_task",
                    models.ForeignKey(
                        help_text="Picking task this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order_fulfillment.pickingtask",
                    ),
                ),
            ],
            options={
                "ordering": ["picking_task", "location"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shipment_number",
                    models.CharField(
                        help_text="Unique shipment identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        help_text="Shipping carrier (FedEx, UPS, DHL, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, help_text="Carrier tracking number", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("LOADED", "Loaded"),
                            ("DISPATCHED", "Dispatched"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                        ],
                        default="CREATED",
                        help_text="Current shipment status",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost of shipping this shipment",
                        max_digits=10,
                    ),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Insurance cost",
                        max_digits=10,
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total shipment weight in kg",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total shipment volume in cubic cm",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ship_from_address",
                    models.JSONField(help_text="Origin address information"),
                ),
                (
                    "ship_to_address",
                    models.JSONField(help_text="Destination address information"),
                ),
                (
                    "manifest",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Shipment manifest with package details and contents",
                    ),
                ),
                (
                    "estimated_delivery_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_delivery_date", models.DateTimeField(blank=True, null=True)),
                (
                    "delivered_by",
                    models.CharField(
                        blank=True,
                        help_text="Person/name who delivered the shipment",
                        max_length=100,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Person who received the shipment",
                        max_length=100,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Shipment notes or special delivery instructions",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional shipment metadata",
                    ),
                ),
                (
                    "dispatcher",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who dispatched the shipment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatched_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order this shipment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="order_fulfillment.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        help_text="Sequence number of package in shipment"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="Package in this shipment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_items",
                        to="order_fulfillment.package",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        help_text="Shipment containing this package",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_items",
                        to="order_fulfillment.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["shipment", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity (Order, PickingTask, Shipment, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="UUID of the entity being audited"),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action performed (created, updated, status_changed, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Previous values before the change",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="New values after the change",
                    ),
                ),
                (
                    "field_changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Specific fields that were changed",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the change"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional audit metadata"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "-timestamp"],
                        name="order_fulfi_entity__d545ed_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="order_fulfi_action_9126d5_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="order_fulfi_user_id_e9f33b_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="order_fulfi_timesta_04954e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "priority"], name="order_fulfi_status_4d5ff5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="order_fulfi_custome_c5b853_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="order_fulfi_created_d76e89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="order_fulfi_order_n_0cc00e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product_sku"], name="order_fulfi_order_i_3323a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["quantity_allocated", "quantity_picked"],
                name="order_fulfi_quantit_ef5185_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product_id")},
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["order", "status"], name="order_fulfi_order_i_8f1f57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["warehouse_id", "location"],
                name="order_fulfi_warehou_be76b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["reservation_id"], name="order_fulfi_reserva_79b924_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["status", "allocated_at"], name="order_fulfi_status_8871cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packageitem",
            index=models.Index(
                fields=["package", "order_item"], name="order_fulfi_package_e4c23e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packageitem",
            unique_together={("package", "order_item")},
        ),
        migrations.AddIndex(
            model_name="packingtask",
            index=models.Index(fields=["status"], name="order_fulfi_status_ed4b54_idx"),
        ),
        migrations.AddIndex(
            model_name="packingtask",
            index=models.Index(
                fields=["packer", "status"], name="order_fulfi_packer__f04781_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packingtask",
            index=models.Index(
                fields=["order", "status"], name="order_fulfi_order_i_977c3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["packing_task", "is_sealed"],
                name="order_fulfi_packing_c33a50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["package_number"], name="order_fulfi_package_e3ecc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickingtask",
            index=models.Index(
                fields=["status", "priority"], name="order_fulfi_status_7630e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickingtask",
            index=models.Index(
                fields=["picker", "status"], name="order_fulfi_picker__ef3fb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickingtask",
            index=models.Index(
                fields=["order", "status"], name="order_fulfi_order_i_34663f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickingtask",
            index=models.Index(
                fields=["warehouse_id", "zone"], name="order_fulfi_warehou_ea2fa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickingitem",
            index=models.Index(
                fields=["picking_task", "is_completed"],
                name="order_fulfi_picking_50bfc5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pickingitem",
            index=models.Index(
                fields=["order_item"], name="order_fulfi_order_i_0b240b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pickingitem",
            unique_together={("picking_task", "order_item")},
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["status", "estimated_delivery_date"],
                name="order_fulfi_status_9665ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["carrier", "tracking_number"],
                name="order_fulfi_carrier_98f3a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["order", "status"], name="order_fulfi_order_i_04716e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["dispatched_at"], name="order_fulfi_dispatc_2a76a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentitem",
            index=models.Index(
                fields=["shipment", "sequence_number"],
                name="order_fulfi_shipmen_0abc78_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shipmentitem",
            unique_together={("shipment", "package")},
        ),
    ]
