# Generated by Django 5.2.7 on 2025-12-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ASN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asn_number",
                    models.CharField(
                        help_text="Unique ASN identifier", max_length=20, unique=True
                    ),
                ),
                ("carrier_name", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=50)),
                ("vehicle_number", models.CharField(blank=True, max_length=20)),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("driver_phone", models.CharField(blank=True, max_length=15)),
                ("expected_ship_date", models.DateField()),
                ("actual_ship_date", models.DateField(blank=True, null=True)),
                ("expected_arrival_date", models.DateField()),
                ("actual_arrival_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("APPROVED", "Approved"),
                            ("IN_TRANSIT", "In Transit"),
                            ("ARRIVED", "Arrived"),
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ASNItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_expected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("item_code", models.CharField(max_length=50)),
                ("item_description", models.CharField(max_length=200)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        help_text="Item condition upon arrival",
                        max_length=50,
                    ),
                ),
                ("quality_notes", models.TextField(blank=True)),
                ("has_damage", models.BooleanField(default=False)),
                ("damage_description", models.TextField(blank=True)),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                (
                    "serial_numbers",
                    models.TextField(
                        blank=True, help_text="Comma-separated serial numbers"
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["item_code"],
            },
        ),
        migrations.CreateModel(
            name="InboundTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_location", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("last_status_update", models.DateTimeField(blank=True, null=True)),
                ("status_notes", models.TextField(blank=True)),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                ("delay_reason", models.TextField(blank=True)),
                ("last_contact", models.DateTimeField(blank=True, null=True)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="WEEKLY",
                        max_length=10,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True, help_text="0=Monday, 6=Sunday", null=True
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(blank=True, help_text="1-31", null=True),
                ),
                ("preferred_time_start", models.TimeField(blank=True, null=True)),
                ("preferred_time_end", models.TimeField(blank=True, null=True)),
                ("default_carrier", models.CharField(blank=True, max_length=100)),
                ("default_driver", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["vendor__name"],
            },
        ),
    ]
