# Generated by Django 5.2.7 on 2025-12-05 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("asn_shipment", "0001_initial"),
        ("vendor_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asn",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_asns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asn",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_asns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asn",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asns",
                to="vendor_management.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="asn",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asns",
                to="vendor_management.vendor",
            ),
        ),
        migrations.AddField(
            model_name="asnitem",
            name="asn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="asn_shipment.asn",
            ),
        ),
        migrations.AddField(
            model_name="asnitem",
            name="purchase_order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asn_items",
                to="vendor_management.purchaseorderitem",
            ),
        ),
        migrations.AddField(
            model_name="asnitem",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_asn_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inboundtracking",
            name="asn",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking",
                to="asn_shipment.asn",
            ),
        ),
        migrations.AddField(
            model_name="shipmentschedule",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment_schedules",
                to="vendor_management.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="asn",
            index=models.Index(
                fields=["asn_number"], name="asn_shipmen_asn_num_96bb1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asn",
            index=models.Index(fields=["status"], name="asn_shipmen_status_b8ff0c_idx"),
        ),
        migrations.AddIndex(
            model_name="asn",
            index=models.Index(
                fields=["expected_arrival_date"], name="asn_shipmen_expecte_f12cb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asn",
            index=models.Index(
                fields=["vendor"], name="asn_shipmen_vendor__d68f5e_idx"
            ),
        ),
    ]
