# Generated by Django 5.2.9 on 2025-12-05 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemandeAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("date_creation", models.DateField(auto_now_add=True)),
                ("service_demandeur", models.CharField(max_length=100)),
                ("objet", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE", "En attente validation"),
                            ("VALIDE", "Validée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BonCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("date_emission", models.DateField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ENVOYE", "Envoyé au fournisseur"),
                            ("CONFIRME", "Confirmé"),
                            ("CLOTURE", "Clôturé"),
                        ],
                        default="ENVOYE",
                        max_length=20,
                    ),
                ),
                (
                    "demande_achat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="achats.demandeachat",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="achats.fournisseur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneDemandeAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField()),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="achats.demandeachat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reception", models.DateField(auto_now_add=True)),
                ("quantites_conformes", models.BooleanField(default=True)),
                (
                    "bon_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="achats.boncommande",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LitigeReception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_creation", models.DateField(auto_now_add=True)),
                (
                    "reception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achats.reception",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControleQualite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualite_conforme", models.BooleanField(default=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "reception",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achats.reception",
                    ),
                ),
            ],
        ),
    ]
