# Generated by Django 5.2.7 on 2025-12-05 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("asn_shipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GateQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_number", models.CharField(max_length=10, unique=True)),
                ("vehicle_number", models.CharField(max_length=20)),
                ("trailer_number", models.CharField(blank=True, max_length=20)),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_id", models.CharField(blank=True, max_length=20)),
                ("driver_phone", models.CharField(max_length=15)),
                ("driver_license", models.CharField(blank=True, max_length=20)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("verification_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("CHECKING_IN", "Checking In"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="Lower number = higher priority"
                    ),
                ),
                (
                    "position_in_queue",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("documents_verified", models.BooleanField(default=False)),
                ("vehicle_inspection_passed", models.BooleanField(default=False)),
                ("cargo_inspection_passed", models.BooleanField(default=False)),
                ("check_in_notes", models.TextField(blank=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("issues_found", models.TextField(blank=True)),
                (
                    "estimated_completion_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_completion_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_queues",
                        to="asn_shipment.asn",
                    ),
                ),
                (
                    "check_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("ARRIVAL", "Vehicle Arrival"),
                            ("CHECK_IN_START", "Check-in Started"),
                            ("DOCUMENT_VERIFICATION", "Document Verification"),
                            ("VEHICLE_INSPECTION", "Vehicle Inspection"),
                            ("APPROVAL", "Approval Granted"),
                            ("REJECTION", "Entry Rejected"),
                            ("DEPARTURE", "Vehicle Departure"),
                            ("OTHER", "Other Activity"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gate_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="gate_checkin.gatequeue",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ASN", "Advance Shipment Notice"),
                            ("PO", "Purchase Order"),
                            ("DELIVERY_NOTE", "Delivery Note"),
                            ("INVOICE", "Invoice"),
                            ("DRIVER_LICENSE", "Driver License"),
                            ("VEHICLE_REGISTRATION", "Vehicle Registration"),
                            ("INSURANCE", "Insurance Certificate"),
                            ("CUSTOMS_DOCS", "Customs Documents"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=50)),
                ("is_present", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True)),
                ("issues_found", models.TextField(blank=True)),
                ("attachment_urls", models.JSONField(blank=True, default=list)),
                (
                    "verified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gate_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="gate_checkin.gatequeue",
                    ),
                ),
            ],
            options={
                "ordering": ["document_type"],
            },
        ),
        migrations.CreateModel(
            name="VehicleInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("PRE_ARRIVAL", "Pre-Arrival"),
                            ("GATE_CHECK", "Gate Check"),
                            ("POST_LOADING", "Post Loading"),
                            ("DEPARTURE", "Departure"),
                        ],
                        max_length=15,
                    ),
                ),
                ("exterior_condition", models.TextField(blank=True)),
                ("interior_condition", models.TextField(blank=True)),
                ("tire_condition", models.TextField(blank=True)),
                ("brake_condition", models.TextField(blank=True)),
                ("lights_condition", models.TextField(blank=True)),
                ("fire_extinguisher", models.BooleanField(default=False)),
                ("first_aid_kit", models.BooleanField(default=False)),
                ("warning_triangles", models.BooleanField(default=False)),
                ("spare_tire", models.BooleanField(default=False)),
                ("passed_inspection", models.BooleanField(default=False)),
                ("critical_issues", models.TextField(blank=True)),
                ("recommended_actions", models.TextField(blank=True)),
                ("inspection_notes", models.TextField(blank=True)),
                ("photo_urls", models.JSONField(blank=True, default=list)),
                (
                    "inspected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "gate_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="gate_checkin.gatequeue",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-inspected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="gatequeue",
            index=models.Index(
                fields=["queue_number"], name="gate_checki_queue_n_99ec34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gatequeue",
            index=models.Index(fields=["status"], name="gate_checki_status_43153c_idx"),
        ),
        migrations.AddIndex(
            model_name="gatequeue",
            index=models.Index(
                fields=["created_at"], name="gate_checki_created_a9fe75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gatequeue",
            index=models.Index(fields=["asn"], name="gate_checki_asn_id_beabfe_idx"),
        ),
        migrations.AddIndex(
            model_name="gatelog",
            index=models.Index(
                fields=["gate_queue", "timestamp"],
                name="gate_checki_gate_qu_ece8a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gatelog",
            index=models.Index(
                fields=["activity"], name="gate_checki_activit_326793_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentverification",
            unique_together={("gate_queue", "document_type")},
        ),
    ]
