# Generated by Django 6.0 on 2025-12-06 00:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('zone', 'Zone'), ('aisle', 'Aisle'), ('rack', 'Rack'), ('level', 'Level'), ('bin', 'Bin')], max_length=20)),
                ('storage_type', models.CharField(choices=[('pallet', 'Pallet'), ('box', 'Box'), ('bulk', 'Bulk')], max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_unit', models.CharField(default='piece', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_categories', models.ManyToManyField(blank=True, related_name='allowed_locations', to='products.productcategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='warehouse.storagelocation')),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'db_table': 'storage_locations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('putaway', 'Putaway'), ('relocation', 'Relocation'), ('picking', 'Picking'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='warehouse.storagelocation')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='warehouse.storagelocation')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_movement_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='warehouse.storagelocation')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='PutawayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('storage_type', models.CharField(choices=[('pallet', 'Pallet'), ('box', 'Box'), ('bulk', 'Bulk')], max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Lowest')], default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_rules', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Putaway Rule',
                'verbose_name_plural': 'Putaway Rules',
                'db_table': 'putaway_rules',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['product_category', 'storage_type', 'is_active'], name='putaway_rul_product_6486d2_idx'), models.Index(fields=['priority'], name='putaway_rul_priorit_989194_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['code'], name='storage_loc_code_64fbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['level'], name='storage_loc_level_417c96_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['is_active'], name='storage_loc_is_acti_b65ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['parent'], name='storage_loc_parent__f98aad_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at'], name='stock_movem_created_8de937_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product'], name='stock_movem_product_911dad_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['from_location'], name='stock_movem_from_lo_261c55_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['to_location'], name='stock_movem_to_loca_4d9a73_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['user'], name='stock_movem_user_id_4fa986_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['location', 'product'], name='stock_items_locatio_3730cc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['product'], name='stock_items_product_33e0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['location'], name='stock_items_locatio_aa0443_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('location', 'product')},
        ),
    ]
